name: Build

on:
  pull_request:
  
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore ./Farfetch.IdentityServer.Contrib.TokenExchange.sln
      
    - name: Build
      run: dotnet build ./Farfetch.IdentityServer.Contrib.TokenExchange.sln -c Release
      
    - name: Test
      run: dotnet test tests/Farfetch.IdentityServer.Contrib.TokenExchange.Tests/Farfetch.IdentityServer.Contrib.TokenExchange.Tests.csproj -c Release --no-restore --verbosity normal