name: Build

on:
  pull_request:
  
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.0'

    - name: Install dependencies
      run: dotnet restore ./Duende.IdentityServer.Contrib.TokenExchange.sln
      
    - name: Build
      run: dotnet build ./Duende.IdentityServer.Contrib.TokenExchange.sln -c Release
      
    - name: Test
      run: dotnet test tests/Duende.IdentityServer.Contrib.TokenExchange.Tests/Duende.IdentityServer.Contrib.TokenExchange.Tests.csproj -c Release --no-restore --verbosity normal