name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore ./Duende.IdentityServer.Contrib.TokenExchange.sln
    
    - name: Test
      run: dotnet test tests/Duende.IdentityServer.Contrib.TokenExchange.Tests/Duende.IdentityServer.Contrib.TokenExchange.Tests.csproj -c Release --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack ./Duende.IdentityServer.Contrib.TokenExchange.sln -c Release /p:Version=${{ github.event.release.tag_name }} -o ./drop

    - name: Publish
      run: dotnet nuget push */*.nupkg -k ${{ secrets.NUGET_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json

    - name: Print Version
      run: echo ${{ github.event.release.tag_name }}
